GET http://localhost:3502/employees

###
GET http://localhost:3502/employees/1

###
POST http://localhost:3502/employees
Content-Type: application/json

{
    "firstname" : "Prabhakaran",
    "lastname" : "Haribaskar"

}

###
PUT http://localhost:3502/employees
Content-Type: application/json

{   "id": 4,
    "firstname" : "Lakshmi",
    "lastname" : "Thangavel"

}

###
DELETE http://localhost:3502/employees
Content-Type: application/json

{
   "id": 4
}



###
POST http://localhost:3502/register
Content-Type: application/json

{
    "user" : "",
    "pwd" : ""
}

###
POST http://localhost:3502/login
Content-Type: application/json

{
    "user" : "Prabhakar",
    "pwd" : "1605Prabhu@"
}